blog/urls.py
from django.urls import path
from .views import CategoryListView, CategoryDetailView, PostListView, PostDetailView

app_name = "blog"

urlpatterns = [
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path(
        "categories/<slug:slug>/", CategoryDetailView.as_view(), name="category_detail"
    ),
    path("posts/", PostListView.as_view(), name="post_list"),
    path("posts/<slug:slug>/", PostDetailView.as_view(), name="post_detail"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from .views import Homepage

# Admin Site Config
# admin.site.site_header = "Zenith System"
# admin.site.site_title = "Zenith System"
# admin.site.index_title = "Welcome to Zenith System Administrations"


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/auth/", include("users.urls"), name="users"),
    path("api/main/", include("main.urls"), name="main"),
    path("api/management/", include("management.urls"), name="management"),
    path("api/facility/", include("facility.urls"), name="facility"),
    path("api/iot/", include("iot.urls"), name="iot"),
    # blog
    path("blog/", include("blog.urls"), name="blog"),
    # test pages
    path("", Homepage.as_view(), name="homepage"),
    path("notifications/", include("notification.urls"), name="notification"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Spectacular URL Patterns
urlpatterns += [
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        # path("__debug__/", include("debug_toolbar.urls")), # debug toolbar
    ]

iot/urls.py
from django.urls import path
from rest_framework_nested import routers
from iot.views import (
    DeviceTypeViewSet,
    DeviceViewSet,
    RoomDeviceViewSet,
    FacilityDeviceViewSet,
    IoTChannel,
)

app_name = "iot"

router = routers.DefaultRouter()
# device types router
router.register("device-types", DeviceTypeViewSet, basename="device-types")

# devices router
router.register("devices", DeviceViewSet, basename="devices")

# room device router
router.register("room-devices", RoomDeviceViewSet, basename="rooms")

# facility device router
router.register("facility-devices", FacilityDeviceViewSet, basename="facilities")

urlpatterns = [
    path("ws/<str:device_id>/", IoTChannel.as_view(), name="channels"),
] + router.urls

templates/base/_meta.html
<!-- HTML Meta Tags -->
<meta name="description"
    content="ZenithReserve is a robust Hotel Management System developed using Django Rest Framework. It provides a comprehensive solution for managing hotel properties, reservations, billing, and more.">

<!-- Google / Search Engine Tags -->
<meta itemprop="name" content="Zenith System">
<meta itemprop="description"
    content="ZenithReserve is a robust Hotel Management System developed using Django Rest Framework. It provides a comprehensive solution for managing hotel properties, reservations, billing, and more.">
<meta itemprop="image" content="http://sorsauth.sirv.com/Zenith/meta-zenith.png">

<!-- Facebook Meta Tags -->
<meta property="og:url" content="">
<meta property="og:type" content="website">
<meta property="og:title" content="Zenith System">
<meta property="og:description"
    content="ZenithReserve is a robust Hotel Management System developed using Django Rest Framework. It provides a comprehensive solution for managing hotel properties, reservations, billing, and more.">
<meta property="og:image" content="http://sorsauth.sirv.com/Zenith/meta-zenith.png">

<!-- Twitter Meta Tags -->
<meta property="twitter:description"
    content="ZenithReserve is a robust Hotel Management System developed using Django Rest Framework. It provides a comprehensive solution for managing hotel properties, reservations, billing, and more.">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Zenith System">
<meta name="twitter:description"
    content="ZenithReserve is a robust Hotel Management System developed using Django Rest Framework. It provides a comprehensive solution for managing hotel properties, reservations, billing, and more.">
<meta name="twitter:image" content="http://sorsauth.sirv.com/Zenith/meta-zenith.png">


<meta property="description"
    content="ZenithReserve is a robust Hotel Management System developed using Django Rest Framework. It provides a comprehensive solution for managing hotel properties, reservations, billing, and more." />

<meta property="og:description"
    content="ZenithReserve is a robust Hotel Management System developed using Django Rest Framework. It provides a comprehensive solution for managing hotel properties, reservations, billing, and more." />

<meta property="og:url" content="http://sorsauth.sirv.com/Zenith/meta-zenith.png">

templates/base/_navbar.html
<nav class="navbar navbar-expand-lg"
    style="background-color: var(--bs-content-bg); border-bottom: var(--bs-border-width) solid var(--bs-content-border-color);">
    <div class="container-fluid">
        <button type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebar-example"
            class="btn btn-secondary d-md-none">
            <i class="fa-solid fa-gear"></i>
        </button>
        <a class="navbar-brand d-md-none" href="/">
            Zenith System
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-collapse-1"
            aria-controls="navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/admin">Admin</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Blog
                    </a>
                    <ul class="dropdown-menu mt-lg-2 rounded-top-0">
                        <li><a class="dropdown-item" href="{% url 'blog:category_list' %}">Categories</a></li>
                        <li><a class="dropdown-item" href="{% url 'blog:post_list' %}">Posts</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Others</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">IoT</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search docs" aria-label="Search">
                <button class="btn btn-primary" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

templates/base/_sidebar.html
{% load static %}

<nav class="sidebar offcanvas-start offcanvas-md" tabindex="-1" id="sidebar-example">
    <div class="offcanvas-header border-bottom border-secondary border-opacity-25">
        <a class="sidebar-brand" href="#">
            Zenith System
        </a>
        <button type="button" class="btn-close d-md-none" data-bs-dismiss="offcanvas" aria-label="Close"
            data-bs-target="#sidebar-example"></button>
    </div>
    <div class="offcanvas-body">
        <div class="mt-2 mb-3">
            <input type="text" class="form-control" placeholder="Search">
        </div>
        <ul class="sidebar-nav">
            <li>
                <h6 class="sidebar-header">Getting started</h6>
            </li>
            <li>
                <hr class="sidebar-divider">
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="#" aria-current="page">Installation</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">CLI commands</a>
            </li>
            <li class="mt-3">
                <h6 class="sidebar-header">Components</h6>
            </li>
            <li>
                <hr class="sidebar-divider">
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">File explorer</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Spreadsheet</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Maps</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Messenger</a>
            </li>
        </ul>
    </div>
</nav>

templates/base/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />

    {% include 'base/_meta.html' %}

    <title>{% block title %} Zenith System {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/halfmoon@2.0.1/css/halfmoon.min.css" rel="stylesheet"
        integrity="sha256-SsJizWSIG9JT9Qxbiy8xnYJfjCAkhEQ0hihxRn7jt2M=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body class="ps-md-sbwidth">

    {% include 'base/_navbar.html' %}
    {% include 'base/_sidebar.html' %}

    <div class="container-fluid mt-2">
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'js/main.js' %}"></script>

    <!-- Option 1: Bootstrap JS bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    -->
</body>

</html>